---

# Remove partitions 

- parted:
    device: /dev/xvdb
    number: 1
    state: absent

- parted:
    device: /dev/xvdb
    number: 2
    state: absent

- parted:
    device: /dev/xvdb
    number: 3
    state: absent

- name: shred data on disk (ceph-disk zap does not work on partial disks)
  shell: shred -v -n1 -z /dev/xvdb
